In [9]:
# Activity 1: Creating Arrays
import numpy as np

a = np.array([10,20,30,40])
print(a)

b = np.arange(1,11)
print(b)

c = np.linspace(0,1,5)
print(c)

[10 20 30 40]
[ 1  2  3  4  5  6  7  8  9 10]
[0.   0.25 0.5  0.75 1.  ]


In [6]:
# Activity 2: Matrix Operation
A = np.array(([1,2],
             [3,4]))

B = np.array(([5,6],
             [7,8]))

print(A+B)
print(A-B)
print(A*B)
print(A@B)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [7]:
# Activity 3: Statistics
marks = np.array([70,65,80.90,88])

print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))
print(np.std(marks))

75.975
88.0
65.0
9.013982194346736


In [8]:
# Activity 4: Statistics on 10 days of temperature data (in °C) for Udupi
import numpy as np

# Maximum daily temperatures in Udupi for the past 10 days (°C)
temp_udupi = np.array([27.5, 28.0, 26.8, 27.2, 28.3, 27.0, 26.5, 27.4, 28.1, 27.8])

# Summary statistics
print("Average Temp:", np.mean(temp_udupi))
print("Standard Deviation:", np.std(temp_udupi))

# Hottest and Coolest Days
hottest_temp = np.max(temp_udupi)
coolest_temp = np.min(temp_udupi)

# Getting the specific day index (1-based index)
hottest_day = np.argmax(temp_udupi) + 1
coolest_day = np.argmax(temp_udupi == coolest_temp) + 1

print(f"Hottest Day: Day {hottest_day} with {hottest_temp}°C")
print(f"Coolest Day: Day {coolest_day} with {coolest_temp}°C")

Average Temp: 27.459999999999997
Standard Deviation: 0.5624944444170097
Hottest Day: Day 5 with 28.3°C
Coolest Day: Day 7 with 26.5°C
